env: minikube
namespace: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  name: eu.gcr.io/ons-rasrmbs-management
  pullPolicy: Always

database:
  managedRedis: false

container:
  port: 8080
service:
  port: 8080
  type: ClusterIP
  loadBalancerIP: "1.2.3.4"
  externalTrafficPolicy: Local

resources:
  requests:
    memory: "256Mi"

sftp:
  test:
    enabled: true