env: minikube
namespace: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedRedis: false

managedRabbitMQ:
  enabled: false

container:
  http:
    port: 8080
  https:
    port: 8443

service:
  http:
    port: 8080
  https:
    port: 8443
  type: ClusterIP
  loadBalancerIP: "1.2.3.4"
  externalTrafficPolicy: Local

resources:
  requests:
    memory: "256Mi"

sftp:
  test:
    enabled: true

ssl:
  cert: MIIJ7QIBAzCCCaYGCSqGSIb3DQEHAaCCCZcEggmTMIIJjzCCBWMGCSqGSIb3DQEHAaCCBVQEggVQMIIFTDCCBUgGCyqGSIb3DQEMCgECoIIE+zCCBPcwKQYKKoZIhvcNAQwBAzAbBBTur+06pxTqKVa6shVkABypaA2TjgIDAMNQBIIEyP/pJ5vbXBBm3p4iR7oKx5HW0mMpeaCzK1+xhFjvASIySHbrK5MHcVSCkxcfqH/DnJUC/pc/6dGtQAt611QK8WboZwwJ1bDq+klxlWnOjoC8iRglDaZ0baL+QmdT1BqgJMOLFcUFCqsnB4dmaT9heAx41SEJz6b3kFbA1GB6g0RblweVkLIw7qwSxz42ylDuj/XMO5wzUerGXB2Jab7cViwXz/zPCX2ACsaOepn2llorKbN8o9nHggX6QQOVDOHQfxTbQj+BP3z3FFX2Ep0CwSROOlBFZ7OPf8FjmaHVD8Pq7kG30ITTzcOg3PuPXqBDvhJfU+T0Bg/YJSQr5oArBrF2fG+Y1rtv8TFkvGoqslmMWXeLELp0CunWQfcS9Vkbrj/AFJvEya3kDx1tv2WYzs+fIIhGxgZ8pkL91F0LOOnx/LvCfhUqtOp/osfZ0YBEdfuyh+rFkyvsJBpPCWY/fnF8ybcQax1bb0jk6TwjbmmbgtlouFLE03sQeTo2ooU9LYueOU4q66TL3rBZO2c29COjQGg+w6mnmI3ylo4tEVvAPCDLUwgdY3x8nUZ8OPYlbY4mWqO4oAkrF7DFFYVE4V1UAJ3unuSa9K0n6ObJdx9bLFDTE5DA0NgE0+zYj0C+Bq2+WO3bRfgwSN8uYfCYBf/TehvMpxbLwDJxCdvOi/bXMPSOvAO0rnaL3OIPX2kD2pgEMxXB87FZ8we6ya/em/IYp8D1rmx+exPnqY8JioGns+GEkkdY7KzkP0c7gEgJlH4X42eVP8utGBUqBTAWZfn5O24teivZausMum4jeagIXvfg7K9V0mCyz4GedBR2vs43+YWzC2DLkd1CEMrAAtprQUb/1sOB/KzGi7mVvtAsRFNkwPGkmhqxgmlcSGzVhUBIbrsLbADweX1z9XKMMCdFVO1/iAKF+CdpUpS4Zyc0mE6fXeywEfYEXHA0fJyguWVFrvGUjpfyhzFK0qit7uSLBgTwwS5Sz+CzrE70SaDsEAOuisu4WIOzc4tMhCD1XCj13GpaAAC5os0wkcwFhBBEpXZTLl7hRM/IwiavO+oIsuPbbUhZ/FUGVXNvWy7oko5kE8xFYE96opuuqsSbSpqwKZCQu9WCQPhsuvIVCOjTN4O1u6E4KWQCJ1mAxFaBFYwxdZHTWmght+daHwY7LwGsaNuggRephRo+g2d3ocBeAWDvF/5JuGwhzegKx/NTAxJ0gxzGKcTTf6HnHT5ENpH/Pm/41uKAYcsYEMF9ta2NehbC0CXD/eTF5jw3eEv0nYXxmDuSatcGYR0nT2kAiCBmM8BYz+lh0VtaHztjVEQiHtngU4yH+7Nsb/ix5DS7O3qHp1ztAjUl2H/lxaOqqCnJ0c8MP6CjAuus4peSoMKHzud3ygXbIoEJQhYPZckHF9JRmAGhg0jU6BurvQzeaOjhsiwP8uHYmuVvirtLX5G7Z1gj/clJumq32KFJFKF5mxtVEN7sqqrFxPCF2QPC6PEIbeYcA8JpgbASzLIFILBsbEhBca4BVsWKXJ6P0EGe+NvbpdfIP7QZCHN3yU1rjL6Vdspr01W8NifHZs1nBTYId3iXKLF6rqvoEYcFfDXfwliJ9Y039LOpGOCQhT0Wq2CBJOOW3mTs2jE6MBUGCSqGSIb3DQEJFDEIHgYAbwBuAHMwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTU5MTE3MTQxMzE1MjCCBCQGCSqGSIb3DQEHBqCCBBUwggQRAgEAMIIECgYJKoZIhvcNAQcBMCkGCiqGSIb3DQEMAQYwGwQUVt0Sc+4UzLIHC0MBGGOpd4q8IyoCAwDDUICCA9AZCkYjNQ1UL64boXIVjqscl9lnjOUmtPD2V//y4BW8Itv1ld3nKFxi5A9nBMe6GZY1OFsn6UwQiZ5YKaAWcqXxTme0yfsj8PrXgPBmfcTw+LwjVuS3lWUZdObml3cuaNK/2eerecZBu0N8/+yWYBfVtmQRwB2HN/V1Wzeeev7Xt4LvvuArQJh0opxSe8YKbzzWFa3n2fybg0wkwXjTvhGUsY5kJSop7eqEJsAcWhzyxTSC89C+Sa12tzbdO62boxx+3Sifk4lH/nj1lOEVYCxhu2Ad+0emPBE++nGD2/CcUsk22SVAAwIBr7N8lFECWYQEIeVYVXV85iOJzGthzwK5BeH82E/oOx+4mD3v6b5QC+7G64JtsyZhg228a8wZEFETmFIE3mZJC6XGlC01OqntE9WpcDlxuPXjQSe7TmIqwI0vVkx0nGAXS/hC5rQyePhXDx7odo8grlHz7MVy2oIH2GQ0I8Ncv/hr5B6dJuirQ0jpnmEMiCTKRCZi30m+xMnadMxQC2Y6eWV7vwY+hD951kE5LWWDLFYKkwvbglDlaawJP3+A3PrJzify5Fo8o6y0Lqw8orvrDiwDxppUZH4LbbjKyrZWBHYBcJ5GUTzlYmqCPQY8SweoLHCQ9KuwUF3EKL5/hyIM9ZhT9BUTF5XUgU/YwLaLJCHwCpLhFTQdOCFfZ4UW7gqlu7kpREFshFkSteigw0OZH9IseNN6gVJA2dZiLTVQ8FT6m9N1mg4q1E5+m8Ob1KGmPH8kZ7rjWWbcIUUYjG2u5Sqcdk2+qW063XkJSVvZan84vRIY7U35lLTsFqiL8uYN9NIVuVEmgB2TZx6qi6JEGSi1/jaBdV4hG/1zRfUwJdS1c1d999rjs0qGPJe4uWSiVYlz9T1kMMJAEBP4CxuFKtFa4MM8NpWGdPeUJVSFrEY/68jyAy2OHU66i5J516SznNJKq4WKr307Ybsv6VHCDI3ulhzX+O9lyQ5YlNQAQNw9Rxs14Ce4NxrXBiouYMrdHlmxSncsjJ7oDW2ifMOjwZW+3prde3SxrcLLzPn8UDeDfmXmPkjrRq6GC3tP/9etxWzOH8ar25s4qkTbw/j3CQ4Vw7GQdzEhEeSLXsLQe68sH3N7UQraQUPyYkjDf/MZCntCalAtkWGtdnDo03W4SxDSbIm2+6C0US+BA3XsCWZqiMqSIKc1JVCR00Rh4y1zI0k7N8hCHuynahhaF5pIVnnVaL4OEuaO7EVmH1TWuoXYJJj3lXvB7AJHJrnqRPZFDGJqRghGrWdTlRhu3wOIMtpFBy270RibMD4wITAJBgUrDgMCGgUABBR7zG8WcysOQS9qCLxthvGj26WpqAQUFBHlNBsTkfMShREW/RXWfUGASMsCAwGGoA==
  password: password
  alias: ons
