env: minikube
namespace: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedRedis: false

managedRabbitMQ:
  enabled: false

container:
  http:
    port: 8080
  https:
    port: 8443

service:
  http:
    port: 8080
  https:
    port: 8443
  type: ClusterIP
  loadBalancerIP: "1.2.3.4"
  externalTrafficPolicy: Local

ssl:
  keystore: "/certs/ons.p12"
  password: password
  alias: ons

resources:
  requests:
    memory: "256Mi"

sftp:
  test:
    enabled: true
