swagger: '2.0'
info:
  title: Survey Data Exchange Gateway API
  description: >
    The Survey Data Exchange (SDX) Gateway provides an interface for the Survey Data Exchange
    to notify Response Management when a questionnaire has been receipted.

    Note that all of the endpoints this service provides are authenticated using HTTP basic authentication.
  version: 9.26.0
schemes:
  - http
basePath: /
produces:
  - application/json
tags:
  - name: Receipt
    description: Questionnaire receipts
paths:
  /questionnairereceipts:
    post:
      summary: Receipt Questionnaire
      description: Records in Response Management that a questionnaire identified by the case Ref has been receipted.
      consumes:
        - application/json
      parameters:
        - name: Accept
          in: header
          description: Response type, application/json
          required: false
          type: string
        - in: body
          name: receipt
          description: Questionnaire receipt to acknowledge
          required: true
          schema:
            $ref: '#/definitions/QuestionnaireReceiptCreationRequest'
      tags:
        - Receipt
      responses:
        204:
          description: Questionnaire receipted
        400:
          description: Invalid input
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  QuestionnaireReceiptCreationRequest:
    type: object
    required:
      - caseRef
    properties:
      caseRef:
        type: string
        description: Unique case identifier
  Error:
    type: object
    properties:
      code:
        description: Error code
        type: string
      timestamp:
        description:  Unique error timestamp that can be searched for in logs
        type: integer
      message:
        description: Error message
        type: string
securityDefinitions:
  UserSecurity:
    type: basic
security:
  - UserSecurity: []
