info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

security:
  basic:
    enabled: false
  user:
    name: gateway
    password: ctp

spring:
  output:
    ansi:
      enabled: never

  application:
    name: Survey Data Exchange Gateway API

  sleuth:
    sampler:
      percentage: 1

  zipkin:
    enabled: false

management:
  security:
    roles: SUPERUSER
    enabled: true
  health:
    rabbit:
      enabled: false

server:
  port: 8191
  servlet-path: /

endpoints:
  autoconfig:
    enabled: true
    sensitive: true
  beans:
    enabled: true
    sensitive: true
  configprops:
    enabled: true
    sensitive: true
  dump:
    enabled: true
    sensitive: true
  env:
    enabled: true
    sensitive: true
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: true
  mappings:
    enabled: true
    sensitive: true
  shutdown:
    enabled: true
    sensitive: true
  trace:
    enabled: true
    sensitive: true

RESPONSE_DATE_TIME_COL_FORMAT: dd/MM/yyyy

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    uk.gov.ons.ctp: INFO
    org.springframework.cloud.sleuth.instrument.messaging.MessagingSpanExtractor: ERROR
    org.springframework.context.annotation.ConfigurationClassPostProcessor: ERROR
  profile: DEV

sftp:
  host: localhost
  port: 122
  username: centos
  password: "JLibV2&XD,"
  directory: Documents
  cron: "* * * * * ?"
  filepattern: "Receipt*.csv"
  
data-grid:
  address: localhost:7379
  lock-time-to-live-seconds: 1800
  
rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 6672
  virtualhost: /

messaging:
  pubMaxAttempts: 3
