info:
  contactEmail: philippe.brossier@ons.gov.uk
  version: ${project.version}
  commit: ${buildNumber}
  branch: ${scmBranch}
  buildTime: ${timestamp}

security:
  basic:
    enabled: false
  user:
    name: gateway
    password: ctp

spring:
  output:
    ansi:
      enabled: never

  application:
    name: Survey Data Exchange Gateway API

  sleuth:
    sampler:
      percentage: 1

  zipkin:
    enabled: false

management:
  port: 8291
  context-path: /mgmt
  security:
    roles: SUPERUSER
    enabled: true
  health:
    rabbit:
      enabled: false

server:
  port: 8191
  servlet-path: /

endpoints:
  enabled: true
  sensitive: true

RESPONSE_DATE_TIME_COL_FORMAT: dd/MM/yyyy

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    uk.gov.ons.ctp: debug
    org.springframework.cloud.sleuth.instrument.messaging.MessagingSpanExtractor: ERROR
    org.springframework.context.annotation.ConfigurationClassPostProcessor: ERROR

sftp:
  host: localhost
  port: 22
  username: centos
  password: "JLibV2&XD,"
  directory: Documents
  cron: "* * * * * ?"
  filepattern: "Receipt*.csv"
  
data-grid:
  address: localhost:6379
  lock-time-to-live-seconds: 1800
  
rabbitmq:
  username: guest
  password: guest
  host: localhost
  virtualhost: /

messaging:
  pubMaxAttempts: 3
