info:
  contactEmail: philippe.brossier@ons.gov.uk
  version: ${project.version}
  commit: ${buildNumber}
  branch: ${scmBranch}
  buildTime: ${timestamp}

spring:
  application:
    name: Survey Data Exchange Gateway

server:
  port: 8191


management:
  port: 8291
  context-path: /mgmt
