info:
  contactEmail: philippe.brossier@ons.gov.uk
  version: ${project.version}
  commit: ${buildNumber}
  branch: ${scmBranch}
  buildTime: ${timestamp}

security:
  basic:
    enabled: true
  user:
    name: admin
    password: ctp

spring:
  application:
    name: Survey Data Exchange Gateway API

  sleuth:
    sampler:
      percentage: 1

  zipkin:
    enabled: true # true is the default to post to a Zipkin server at 9411

management:
  port: 8291
  context-path: /mgmt

server:
  port: 8191
  servlet-path: /mgmt

endpoints:
  enabled: true
  sensitive: true

CASE_REF_COL_NAME: caseRef
RESPONSE_DATE_TIME_COL_NAME: responseDateTime
