info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}
    
management:
  health:
    rabbit:
      enabled: false
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 8191
    
spring:
  output:
    ansi:
      enabled: never
  application:
    name: ONS SDX Gateway API
  security:
    user:
      name: admin
      password: secret
  mvc:
    servlet:
      path: /
  
data-grid:
  address: ${cloud.services.redis.connection.host}:${cloud.services.redis.connection.port}
  lock-time-to-live-seconds: 1800
  
rabbitmq:
  username: ${cloud.services.rabbitmq.connection.username}
  password: ${cloud.services.rabbitmq.connection.password}
  host: ${cloud.services.rabbitmq.connection.host}
  port: ${cloud.services.rabbitmq.connection.port}
  virtualhost: ${cloud.services.rabbitmq.connection.virtualhost}
  
messaging:
  pubMaxAttempts: 3
  
  