info:
  contactEmail: philippe.brossier@ons.gov.uk
  version: ${project.version}
  commit: ${buildNumber}
  branch: ${scmBranch}
  buildTime: ${timestamp}

security:
  basic:
    enabled: true
  user:
    name: admin
    password: ctp

spring:
  application:
    name: Survey Data Exchange Gateway API

management:
  port: 8291
  context-path: /mgmt

server:
  port: 8191
  servlet-path: /mgmt

endpoints:
  enabled: true
  sensitive: true
