---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: self-signed-cert
  namespace: {{ .Values.namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcp.project }}
  data:
    - key: ssl-cert
      name: cert.p12
      version: latest

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ssl-secret
  namespace: {{ .Values.namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcp.project }}
  data:
    - key: ssl-secret
      name: password
      version: latest
      property: password
    - key: ssl-secret
      name: alias
      version: latest
      property: alias
