{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: sdx-gateway-ip
    kubernetes.io/ingress.class: "gce-internal"
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ .Chart.Name }}
              servicePort: {{ .Values.service.port }}
  {{- end }}
