apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  {{- if eq $.Values.service.type "LoadBalancer" }}
  annotations:
    cloud.google.com/load-balancer-type: Internal
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq $.Values.service.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.http.port }}
    targetPort: {{ .Values.container.http.port }}
    protocol: TCP
    {{- if eq $.Values.service.type "LoadBalancer" }}
  - name: https
    port: {{ .Values.service.https.port }}
    targetPort: {{ .Values.container.https.port }}
    protocol: TCP
    {{- end }}
  selector:
    app: {{ .Chart.Name }}
